services:
  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - '443:443'
    restart: on-failure
    depends_on: 
      - wordpress
    volumes: 
      - wordpress:/var/www/html
    networks:
      - inception-net
  wordpress:
    container_name: wordpress
    build:
      context: wordpress
    env_file:
      - ./wordpress/env
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-net
  mariadb:
    container_name: mariadb
    build:
      context: mariadb
    restart: on-failure
    env_file:
      - ./mariadb/.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-net
